package de.danoeh.antennapod.model.feed;

import androidx.annotation.ColorInt;

/**
 * Represents metadata for a queue in the multiple queues feature.
 *
 * Each queue has a unique identifier, user-defined name, color for UI identification,
 * creation timestamp, display order, and tracking of currently playing episode(s).
 *
 * Stored in QueueMetadata table in the database.
 */
public class QueueMetadata {

    /**
     * Sentinel value indicating no episode is currently playing in a queue.
     */
    public static final long NO_MEDIA_PLAYING = -1;

    /**
     * Unique queue identifier. Auto-generated by database.
     * Immutable after creation.
     */
    private final long id;

    /**
     * User-defined queue name (e.g., "Workout", "Commute").
     * Cannot be null or empty string.
     * Mutable - can be changed via setName().
     */
    private String name;

    /**
     * RGB color value for UI queue identification.
     * Stored as INTEGER (e.g., 0xFFAA3344).
     * Cannot be null.
     * Mutable - can be changed via setColor().
     */
    @ColorInt
    private int color;

    /**
     * Unix timestamp (milliseconds) when this queue was created.
     * Immutable after creation.
     */
    private final long createdAt;

    /**
     * User-defined display order for queues in UI (0-indexed).
     * Must be unique across all queues.
     * Mutable - can be changed when reordering queues.
     */
    private int sortOrder;

    /**
     * FeedMedia ID of the currently playing episode in this queue.
     * -1 if no episode is playing.
     * Mutable - updated when playback starts/stops.
     */
    private long currentlyPlayingFeedMediaId;

    /**
     * Feed ID of the currently playing episode in this queue.
     * -1 if no episode is playing.
     * Mutable - updated when playback starts/stops.
     */
    private long currentlyPlayingFeedId;

    /**
     * Create a QueueMetadata with all fields.
     *
     * @param id                            Unique queue identifier (auto-generated, usually from database)
     * @param name                          User-defined queue name (cannot be null or empty)
     * @param color                         RGB color value for UI
     * @param createdAt                     Unix timestamp (milliseconds) when queue was created
     * @param sortOrder                     Display order (0-indexed, must be unique across queues)
     * @param currentlyPlayingFeedMediaId   FeedMedia ID of currently playing episode, or -1 if none
     * @param currentlyPlayingFeedId        Feed ID of currently playing episode, or -1 if none
     *
     * @throws IllegalArgumentException if name is null or empty string
     */
    public QueueMetadata(long id, String name, @ColorInt int color, long createdAt,
                        int sortOrder, long currentlyPlayingFeedMediaId,
                        long currentlyPlayingFeedId) {
        if (name == null || name.trim().isEmpty()) {
            throw new IllegalArgumentException("Queue name cannot be null or empty");
        }
        this.id = id;
        this.name = name;
        this.color = color;
        this.createdAt = createdAt;
        this.sortOrder = sortOrder;
        this.currentlyPlayingFeedMediaId = currentlyPlayingFeedMediaId;
        this.currentlyPlayingFeedId = currentlyPlayingFeedId;
    }

    /**
     * Create a QueueMetadata without currently playing episode tracking.
     * Used when creating a new queue before any episodes have been played.
     *
     * @param id        Unique queue identifier
     * @param name      User-defined queue name (cannot be null or empty)
     * @param color     RGB color value for UI
     * @param createdAt Unix timestamp (milliseconds) when queue was created
     * @param sortOrder Display order (0-indexed, must be unique across queues)
     *
     * @throws IllegalArgumentException if name is null or empty string
     */
    public QueueMetadata(long id, String name, @ColorInt int color, long createdAt,
                        int sortOrder) {
        this(id, name, color, createdAt, sortOrder, NO_MEDIA_PLAYING, NO_MEDIA_PLAYING);
    }

    /**
     * @return Unique queue identifier
     */
    public long getId() {
        return id;
    }

    /**
     * @return User-defined queue name
     */
    public String getName() {
        return name;
    }

    /**
     * Set queue name.
     *
     * @param name New queue name (cannot be null or empty)
     * @throws IllegalArgumentException if name is null or empty string
     */
    public void setName(String name) {
        if (name == null || name.trim().isEmpty()) {
            throw new IllegalArgumentException("Queue name cannot be null or empty");
        }
        this.name = name;
    }

    /**
     * @return RGB color value for UI
     */
    @ColorInt
    public int getColor() {
        return color;
    }

    /**
     * Set queue color.
     *
     * @param color RGB color value
     */
    public void setColor(@ColorInt int color) {
        this.color = color;
    }

    /**
     * @return Unix timestamp (milliseconds) when this queue was created
     */
    public long getCreatedAt() {
        return createdAt;
    }

    /**
     * @return Display order (0-indexed)
     */
    public int getSortOrder() {
        return sortOrder;
    }

    /**
     * Set display order.
     *
     * @param sortOrder New display order (must be unique across all queues)
     */
    public void setSortOrder(int sortOrder) {
        this.sortOrder = sortOrder;
    }

    /**
     * @return FeedMedia ID of currently playing episode, or -1 if none
     */
    public long getCurrentlyPlayingFeedMediaId() {
        return currentlyPlayingFeedMediaId;
    }

    /**
     * Set currently playing FeedMedia ID.
     *
     * @param currentlyPlayingFeedMediaId FeedMedia ID, or -1 if no episode playing
     */
    public void setCurrentlyPlayingFeedMediaId(long currentlyPlayingFeedMediaId) {
        this.currentlyPlayingFeedMediaId = currentlyPlayingFeedMediaId;
    }

    /**
     * @return Feed ID of currently playing episode, or -1 if none
     */
    public long getCurrentlyPlayingFeedId() {
        return currentlyPlayingFeedId;
    }

    /**
     * Set currently playing Feed ID.
     *
     * @param currentlyPlayingFeedId Feed ID, or -1 if no episode playing
     */
    public void setCurrentlyPlayingFeedId(long currentlyPlayingFeedId) {
        this.currentlyPlayingFeedId = currentlyPlayingFeedId;
    }

    /**
     * Check if an episode is currently playing in this queue.
     *
     * @return true if currentlyPlayingFeedMediaId != NO_MEDIA_PLAYING, false otherwise
     */
    public boolean isEpisodePlaying() {
        return currentlyPlayingFeedMediaId != NO_MEDIA_PLAYING;
    }

    /**
     * Clear currently playing episode tracking.
     * Used when queue is deleted or when stopping playback.
     */
    public void clearCurrentlyPlaying() {
        currentlyPlayingFeedMediaId = NO_MEDIA_PLAYING;
        currentlyPlayingFeedId = NO_MEDIA_PLAYING;
    }

    @Override
    public String toString() {
        return "QueueMetadata{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", color=" + color +
                ", createdAt=" + createdAt +
                ", sortOrder=" + sortOrder +
                ", currentlyPlayingFeedMediaId=" + currentlyPlayingFeedMediaId +
                ", currentlyPlayingFeedId=" + currentlyPlayingFeedId +
                '}';
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof QueueMetadata)) return false;

        QueueMetadata that = (QueueMetadata) o;
        return id == that.id;
    }

    @Override
    public int hashCode() {
        return Long.hashCode(id);
    }
}
